In [1]:
import numpy as np

# Looping Through Arrays

In [2]:
# Create a two-dimensional array named arrA.
arrA = np.array([[11, 12, 13], [14, 15, 16]]) 
print(arrA)  # Print the array

[[11 12 13]
 [14 15 16]]


In [3]:
# Loop through the first dimension of arrA and print each element multiplied by 2.
for x in arrA:  # Each 'x' represents a row in the array
  print(x * 2)  # Multiply each row by 2 and print the result

[22 24 26]
[28 30 32]


In [4]:
# Loop through the second dimension of arrA and print each element multiplied by 2.
for x in arrA:  # Each 'x' represents a row in the array
  for y in x:  # Each 'y' represents an element within the row
    print(y * 2)  # Multiply each element by 2 and print the result

22
24
26
28
30
32


## The first loop goes through each row of the array as if it's one item. The second loop looks at each number in the array individually.

In [5]:
for x in arrA:
  for y in x:
    loop_result = x * 2
    print(loop_result)

# This code iterates through each number in arrA and multiplies it by 2.
# The result is different from the previous code because it performs a calculation on each number, rather than simply printing the number itself.
# In this case, the result is a series of individual numbers, each doubled. This is different from the previous code, where the result was a series of arrays, each with its elements doubled.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


# Joining and Stacking Arrays

In [6]:
# Create joined_array_1 by concatenating arrA with itself on axis=0 (the default axis)
joined_array_1 = np.concatenate((arrA, arrA), axis=0)  # Join the arrays vertically
print(joined_array_1)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
# Create joined_array_2 by concatenating arrA with itself on axis=1
joined_array_2 = np.concatenate((arrA, arrA), axis=1)  # Join the arrays horizontally
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
# Create stacked_array_1 by stacking joined_array_1 with itself
stacked_array_1 = np.stack((joined_array_1, joined_array_1))  # Stack the arrays on a new axis
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
# Trying to stack arrays with different shapes will cause an error!

stacked_array_2 = np.stack((joined_array_1, joined_array_2)) 

#ValueError: all input arrays must have the same shape

# This means I can't stack joined_array_1 and joined_array_2 because they have different numbers of rows and columns.

ValueError: all input arrays must have the same shape

In [ ]:
# Join joined_array_1 and arrA vertically
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array) 

In [ ]:
# Trying to join arrays horizontally with different numbers of rows will cause an error!
another_2 = np.concatenate((joined_array_1, arrA), axis=1) 
# ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2
# The error message basically means the arrays can't be joined sideways because they have different heights (number of rows).

In [ ]:
# Stack arrA with itself side-by-side (horizontally)
stacked_horizontal = np.hstack((arrA, arrA))  
print(stacked_horizontal)

# Stack arrA with itself on top of each other (vertically)
stacked_vertical = np.vstack((arrA, arrA))  
print(stacked_vertical)

# Stack arrA with itself to create a 3D array (depth-wise)
stacked_depth = np.dstack((arrA, arrA))  
print(stacked_depth)

# Splitting Arrays

In [ ]:
# Split joined_array_1 into 2 arrays
splitsky = np.split(joined_array_1, 2)
print(splitsky)

# The result is a list containing 2 arrays. Each array is 2-dimensional and has the same number of columns as joined_array_1, but half the number of rows.

In [ ]:
# Split joined_array_1 into 3 arrays
spliterino = np.split(joined_array_1, 3)
print(spliterino)

# The result is a list containing 3 arrays.
# The first 2 arrays have 1 row and the same number of columns as joined_array_1.The last array has 2 rows and the same number of columns as joined_array_1.
# All 3 arrays are 2-dimensional. Recieved this error code: array split does not result in an equal division

# Searching and Replacing Array Values

In [ ]:
# Use np.where() to find even numbers in arrA
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

# Sorting and Filtering Arrays

In [ ]:
# Create a 2D array arrB
arrB = np.array([[7, 6], [13, 5], [7, 3]])

# Sort arrB and store the result in arrB_sorted
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

In [ ]:
# Print the original arrB
print(arrB)

# Create a boolean array z where elements of arrB are less than 7
z = arrB < 7

# Filter arrB using the boolean array z
arrC = arrB[z]
print(arrC)

In [ ]:
# Print the original arrB
print(arrB)

# Create a boolean array y where elements of arrB are greater than or equal to 7
y = arrB >= 7

# Filter arrB using the boolean array y
arrD = arrB[y]
print(arrD)