In [1]:
import numpy as np

# Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)  # Generate 2 random integers between 1 and 20 (inclusive)
print(r_1)  # Print the generated random numbers

[14 20]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))  # Generate a 1x2 array of random integers between 1 and 20
print(r_2)  # Print the generated 1x2 array

[[ 5 19]]


In [4]:
# Generate a 2x1 array of random floats between 0 and 1
r_3 = np.random.rand(2, 1) 

# Print the array
print(r_3)

[[0.37682556]
 [0.82209727]]


In [5]:
# Generate a 4x5 array of random integers between 20 and 100
r_4 = np.random.randint(20, 101, size=(4, 5))

# Print the array
print(r_4)

[[61 52 78 87 89]
 [69 94 40 68 36]
 [84 58 44 53 85]
 [59 52 63 40 50]]


In [6]:
# Generate a 4x5 array of random floats between 0 and 1
r_5 = np.random.rand(4, 5)

# Print the array
print(r_5)

[[0.21617369 0.11865142 0.0095078  0.34711978 0.23002919]
 [0.83436203 0.47617116 0.36047779 0.52687415 0.11632403]
 [0.20728838 0.20440603 0.72303685 0.79791075 0.37997224]
 [0.27767868 0.39631545 0.95353515 0.78432455 0.54945488]]


# Generating Random Choices from an Array

In [7]:
# Create a 1-D array of student names
students = np.array(['Craig', 'Vanessa', 'Fadil', 'Symone', 'Aron', 'Anthony', 
                    'Hassan', 'Zanib', 'Armando', 'Jacob', 'Caitlian', 'Kaylin'])

# Print the array
print(students)

['Craig' 'Vanessa' 'Fadil' 'Symone' 'Aron' 'Anthony' 'Hassan' 'Zanib'
 'Armando' 'Jacob' 'Caitlian' 'Kaylin']


In [8]:
# Choose a random student from the array
call_on = np.random.choice(students)

# Print the randomly selected student
print(call_on)

Hassan


In [9]:
#Choose a random sample of students for breakout groups
breakout_groups = np.random.choice(students, size=(3, 4))

# Print the breakout groups
print(breakout_groups)

# This might not be the most effective way to assign breakout groups because there's a chance the same student could be assigned to multiple groups.
# np.random.choice samples with replacement by default.

[['Fadil' 'Zanib' 'Aron' 'Anthony']
 ['Symone' 'Caitlian' 'Zanib' 'Armando']
 ['Fadil' 'Armando' 'Aron' 'Symone']]


In [10]:
# Assign probabilities to each student
p = [0.05, 0.1, 0, 0.3, 0.05, 0.1, 0.05, 0.05, 0.1, 0.05, 0.05, 0.10]  

# Craig: 5%
# Vanessa: 10%
# Fadil: 0% (no chance of being called on)
# Symone: 30% (highest chance)
# Aron: 5%
# Anthony: 10%
# Hassan: 5%
# Zanib: 5%
# Armando: 10%
# Jacob: 5%
# Caitlian: 5%
# Kaylin: 10% 


# Make 5 weighted random selections from students
call_on_weighted = np.random.choice(students, size=5, p=p)

# Print the weighted random selections
print(call_on_weighted)

['Symone' 'Anthony' 'Symone' 'Symone' 'Symone']


# Generating a Normal Distribution

In [11]:
# Generate the random distribution
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

# Print the result
print(bell_curve)

[[ 3.60184621 12.62993408  9.34451556  7.29559248  6.52517282]
 [ 9.07652363 13.58735958 10.2437988  12.94106418 16.03570767]
 [ 7.2233964  13.64769889  0.3658602  13.20707602 18.80593631]
 [12.33869468  4.85724325  7.59467774  8.26413743 13.21976241]]
