In [1]:
import numpy as np

# Sample Arrays

In [2]:
# Create a variable named r_1 that contains a random set of integers between 1 and 20 with a size of 2 elements. Print r_1.
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

# Create a variable named r_2 that contains a random set of integers between 1 and 20 with a size of 1 row, 2 columns. Print r_2.
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

# Create a variable named r_3 that contains a random set of floats between 0 and 1 with a size of 2 rows, 1 column. Print r_3.
r_3 = np.random.rand(2, 1)
print(r_3)

# Create a variable named r_4 that contains a random set of integers between 20 and 100 with a size of 4 rows, 5 columns. Print r_4.
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

# Create a variable named r_5 that contains a random set of floats between 0 and 1 with a size of 4 rows, 5 columns. Print r_5.
r_5 = np.random.rand(4, 5)
print(r_5)

[ 3 10]
[[15 12]]
[[0.88186088]
 [0.62404395]]
[[88 63 99 32 21]
 [83 95 91 92 96]
 [42 86 65 87 45]
 [45 86 85 34 44]]
[[0.26148054 0.10967254 0.08575175 0.48305651 0.86505895]
 [0.1924794  0.40846701 0.69925804 0.05137919 0.59640166]
 [0.90716202 0.54047263 0.2350462  0.91795546 0.46668714]
 [0.47561361 0.79198861 0.21870297 0.29867121 0.10063603]]


# Permutations

In [3]:
print(r_4)

[[88 63 99 32 21]
 [83 95 91 92 96]
 [42 86 65 87 45]
 [45 86 85 34 44]]


In [4]:
np.random.shuffle(r_4)
print(r_4)

[[83 95 91 92 96]
 [45 86 85 34 44]
 [42 86 65 87 45]
 [88 63 99 32 21]]


The output shows that np.random.shuffle(r_4) shuffled the rows of the array. The values within each row remained the same, but the order of the rows themselves was randomized.
Rows [72 76 31 42 74], [64 78 38 38 57], [64 71 21 99 21], and [75 28 55 38 100] are present in both the original and shuffled arrays. The only difference is their order within the array.

In [5]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[83 95 91 92 96]
 [42 86 65 87 45]
 [88 63 99 32 21]
 [45 86 85 34 44]]
[[83 95 91 92 96]
 [45 86 85 34 44]
 [42 86 65 87 45]
 [88 63 99 32 21]]


I would use shuffle to randomly reorder elements within the original array itself.
I would use permutation to create a new array with randomly reordered elements, keeping the original array intact.

# Mathematical Operations

In [6]:
# Printing r_1 and r_2 as starting values
print("r_1:", r_1)
print("r_2:", r_2)

# Printing the shape of each array
print("Shape of r_1:", r_1.shape)
print("Shape of r_2:", r_2.shape)

# Calculating r_1 plus r_2 using the add function
result = np.add(r_1, r_2)

# Printing the result and its shape
print("Result of r_1 plus r_2:", result)
print("Shape of the result:", result.shape)

r_1: [ 3 10]
r_2: [[15 12]]
Shape of r_1: (2,)
Shape of r_2: (1, 2)
Result of r_1 plus r_2: [[18 22]]
Shape of the result: (1, 2)


In [7]:
# Printing r_1 and r_3 as starting values
print("r_1:", r_1)
print("r_3:", r_3)

# Printing the shape of each array
print("Shape of r_1:", r_1.shape)
print("Shape of r_3:", r_3.shape)

# Calculating r_1 plus r_3 using the add function
result = np.add(r_1, r_3)

# Printing the result and its shape
print("Result of r_1 plus r_3:", result)
print("Shape of the result:", result.shape)

r_1: [ 3 10]
r_3: [[0.88186088]
 [0.62404395]]
Shape of r_1: (2,)
Shape of r_3: (2, 1)
Result of r_1 plus r_3: [[ 3.88186088 10.88186088]
 [ 3.62404395 10.62404395]]
Shape of the result: (2, 2)


In [8]:
# Print r_2 and r_4 as starting values
print("r_2:", r_2)
print("r_4:", r_4)

# Print the shape of each array
print("Shape of r_2:", r_2.shape)
print("Shape of r_4:", r_4.shape)

# Calculate r_2 plus r_4 using the add function
result = np.add(r_2, r_4)

# Print the result and its shape
print("Result of r_2 plus r_4:", result)
print("Shape of the result:", result.shape)

r_2: [[15 12]]
r_4: [[83 95 91 92 96]
 [45 86 85 34 44]
 [42 86 65 87 45]
 [88 63 99 32 21]]
Shape of r_2: (1, 2)
Shape of r_4: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [9]:
result = np.add(r_1, r_4)

# This raised a ValueError because the shapes of r_1 and r_4 are incompatible. r_1 has shape (2,), while r_4 has shape (4, 5). NumPy requires arrays to have the same shape for element-wise addition.

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [12]:
result = np.add(np.array([1]), r_4)
print(result)

[[ 84  96  92  93  97]
 [ 46  87  86  35  45]
 [ 43  87  66  88  46]
 [ 89  64 100  33  22]]


In [13]:
result = np.add(np.array([[1]]), r_4)
print(result)

[[ 84  96  92  93  97]
 [ 46  87  86  35  45]
 [ 43  87  66  88  46]
 [ 89  64 100  33  22]]


In [14]:
result = np.add(np.array([1, 1, 1, 1, 1]), r_4)
print(result)

[[ 84  96  92  93  97]
 [ 46  87  86  35  45]
 [ 43  87  66  88  46]
 [ 89  64 100  33  22]]


In [15]:
#This raised a ValueError because the shapes of the arrays are incompatible.
result = np.add(np.array([[1], [1]]), r_4)

# Error message:
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting is like stretching a smaller array to match the dimensions of a larger one, allowing element-wise operations between arrays of different shapes.

With the add function, each element in the stretched array is added to its corresponding element in the larger array.

The final array's shape depends on how the smaller array was stretched to match the larger one. If the dimensions can't be aligned, an error message is returned.

# Rounding

In [18]:
print(r_3)

[[0.88186088]
 [0.62404395]]


In [19]:
# Rounding the values in r_3 using trunc
rounded_r3 = np.trunc(r_3)

# Printing the rounded array
print(rounded_r3)

[[0.]
 [0.]]


In [20]:
# Rounding the values in r_3 using fix
rounded_r3 = np.fix(r_3)

# Printing the rounded array
print(rounded_r3)

[[0.]
 [0.]]


In [21]:
# Rounding the values in r_3 using floor
rounded_r3 = np.floor(r_3)

# Printing the rounded array
print(rounded_r3)

[[0.]
 [0.]]


In [22]:
# Rounding the values in r_3 using ceil
rounded_r3 = np.ceil(r_3)

# Printing the rounded array
print(rounded_r3)

[[1.]
 [1.]]


In [23]:
# Rounding the values in r_3 using round to 2 decimal places
rounded_r3 = np.round(r_3, 2)

# Printing the rounded array
print(rounded_r3)

[[0.88]
 [0.62]]


#  Cumulative Operations

In [24]:
print(r_4)

[[83 95 91 92 96]
 [45 86 85 34 44]
 [42 86 65 87 45]
 [88 63 99 32 21]]


In [25]:
# Printing the sum of all values in r_4
print("Sum of all values in r_4:", np.sum(r_4))

Sum of all values in r_4: 1379


In [26]:
# Printing the sum of elements along the 0 axis for r_4
print("Sum of elements along the 0 axis for r_4:", np.sum(r_4, axis=0))

Sum of elements along the 0 axis for r_4: [258 330 340 245 206]


In [27]:
# Printing the sum of elements along the 1 axis for r_4
print("Sum of elements along the 1 axis for r_4:", np.sum(r_4, axis=1))


Sum of elements along the 1 axis for r_4: [457 294 325 303]


In [28]:
# Printing the cumulative sum (rolling total) of values in r_4
print("Cumulative sum of values in r_4:", np.cumsum(r_4))

Cumulative sum of values in r_4: [  83  178  269  361  457  502  588  673  707  751  793  879  944 1031
 1076 1164 1227 1326 1358 1379]


In [29]:
# Printing the cumulative sum (rolling total) of values along the 0 axis for r_4
print("Cumulative sum of values along the 0 axis for r_4:", np.cumsum(r_4, axis=0))

Cumulative sum of values along the 0 axis for r_4: [[ 83  95  91  92  96]
 [128 181 176 126 140]
 [170 267 241 213 185]
 [258 330 340 245 206]]


# Grocery Problem

In [31]:
# Creating bag1 and bag2 arrays with specific food types and brands
bag1 = np.array([['Gala Apples', 'Blueberries', 'Cutie Oranges','Spinach', 'Brussel Sprouts', 'Goldfish', 'Lays Potato Chips', 'Chips Ahoy']])
bag2 = np.array([['Broccoli', 'Green Beans', 'Carrots', 'Celery', 'Pepsi', 'Gatorade', 'Cheez-Its']])

# Printing bag1 and bag2
print("Bag 1:", bag1)
print("Bag 2:", bag2)

Bag 1: [['Gala Apples' 'Blueberries' 'Cutie Oranges' 'Spinach' 'Brussel Sprouts'
  'Goldfish' 'Lays Potato Chips' 'Chips Ahoy']]
Bag 2: [['Broccoli' 'Green Beans' 'Carrots' 'Celery' 'Pepsi' 'Gatorade'
  'Cheez-Its']]


In [32]:
# Calculating the total number of items in each bag
total_items_bag1 = np.size(bag1)
total_items_bag2 = np.size(bag2)

# Printing the results
print("The first bag contains", total_items_bag1, "items, and the second bag contains", total_items_bag2, "items")

The first bag contains 8 items, and the second bag contains 7 items


In [33]:
# Creating bag1 and bag2 arrays
bag1 = np.array([2, 3, 4, 0])  # Vegetables, Fruits, Snacks, Beverages
bag2 = np.array([4, 0, 1, 2])  # Vegetables, Fruits, Snacks, Beverages

# Calculating the total number of items in each category
total_vegetables = bag1[0] + bag2[0]
total_fruits = bag1[1] + bag2[1]
total_snacks = bag1[2] + bag2[2]
total_beverages = bag1[3] + bag2[3]

# Printing the results
print("There are", total_vegetables, "vegetables,", total_fruits, "fruits,", total_snacks,
      "boxes of snacks, and", total_beverages, "beverages in the two grocery bags")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


# Teamwork

In [34]:
# Creating a variable holding an array of Ali's door-knocking data
ali_doors = np.array([5, 4, 6, 4, 2])

# Printing the array
print("Ali's door-knocking data:", ali_doors)

Ali's door-knocking data: [5 4 6 4 2]


In [36]:
# Creating a variable holding an array of Ben's door-knocking data (including Monday)
ben_doors = np.array([0, 5, 5, 3, 4])

# Printing the array
print("Ben's door-knocking data:", ben_doors)

Ben's door-knocking data: [0 5 5 3 4]


In [37]:
# Creating a variable holding an array of Carla's door-knocking data (including Wednesday)
carla_doors = np.array([3, 6, 0, 3, 4])

# Printing the array
print("Carla's door-knocking data:", carla_doors)

Carla's door-knocking data: [3 6 0 3 4]


In [38]:
# Creating an array containing all door-knocks for the week
all_knocks = np.array([ali_doors, ben_doors, carla_doors])

# Printing the resulting array
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [39]:
# Calculating the total number of doors knocked on by each person
total_knocks_per_person = np.sum(all_knocks, axis=1)

# Calculating the total number of doors knocked on by the group
total_knocks_group = np.sum(all_knocks)

# Printing the results
print("Total doors knocked on by each person:", total_knocks_per_person)
print("Total doors knocked on by the group:", total_knocks_group)

Total doors knocked on by each person: [21 17 16]
Total doors knocked on by the group: 54


In [45]:
# Calculate the total estimated votes per day
total_estimated_votes_per_day = np.sum(all_knocks, axis=0) / 2

# Print the results
print("Total estimated votes per day:", total_estimated_votes_per_day)

Total estimated votes per day: [4.  7.5 5.5 5.  5. ]
